### ISSUE TITLE
autobalance.lua mod causes the server to hang

### ISSUE THREAD

**Issue by obstriegel** [benzomatic/spaghettimod-extra#1]
I tried the autobalance mod but it makes the server hang at some point.
It enters some kind of endless loop I guess, causing it to eat 100% CPU and being completely unresponsive so I have to kill it manually.

The last function called is "determine_worst_players", the only function with a while loop in it which has some condition to change n.

https://github.com/benzomatic/spaghettimod-extra/blob/master/script/std/autobalance.lua#L46

**Comment by pitchdetector** [comment]
Ich habe lua heute zum ersten mal gelesen, aber sollte die n irgendwann num erreichen, wenn es mindestens ein spectator dabei ist? XPEH_BAM

**Comment by benzomatic** [comment]
Should be fixed in https://github.com/benzomatic/spaghettimod-extra/commit/9d665bbb3fe5dafc658ae46e858168cc95213e29, please try again!
